### PR TITLE
Koa@2

### PR DESCRIPTION
**Pull request by coderhaoxin**
Maybe it's better to write with `babel` + `async` ?

### CODE REVIEW

**Comment by tejasmanohar** [comment]
I use async/await for pretty much all Koa 2 middleware that I write outside of this org, but it seems we don't wanna use Babel in KoaJS official stuff yet... unless we vote on it again and decide otherwise. Basically, I suggest whatever we do, we're consistent on this decision amongst all official middleware.

// cc @jonathanong

**Comment by coderhaoxin** [comment]
Just as discussed in https://github.com/koajs/etag/pull/16, this looks like callback style :cry: .

**Comment by tejasmanohar** [comment]
Agreed @coderhaoxin - I'm also not so content with how the new Promise-based middleware is looking here without async/await. Hopefully, we can resolve the policy for using async/await other middleware in the org rather than just Koa core in that issue :)

**Comment by coderhaoxin** [comment]
> we can resolve the policy for using async/await other middleware in the org rather than just Koa core in that issue

@tejasmanohar +1

**Comment by tejasmanohar** [comment]
@coderhaoxin +1 / vote on the other thread :)

**Comment by coderhaoxin** [comment]
according to https://github.com/koajs/koa/issues/603, land on https://github.com/koajs/mount/tree/next

**Comment by niftylettuce** [comment]
what happened to @next support?

**Comment by coderhaoxin** [comment]
https://github.com/koajs/mount/issues/33

**Comment by coderhaoxin** [comment]
https://github.com/koajs/mount/issues/39

**Pull request closed without merging**
